// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCStQ-Sub07b7R9cSb7Ijo8ZsVlTxS-JM',
    appId: '1:177000950878:web:f5825ca0ec8410c87d58cf',
    messagingSenderId: '177000950878',
    projectId: 'flashfeed-16793',
    authDomain: 'flashfeed-16793.firebaseapp.com',
    storageBucket: 'flashfeed-16793.appspot.com',
    measurementId: 'G-68ZLJTPS5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkWTQWpY9IeFM3oEj2hiqpSs0JeIpGnKw',
    appId: '1:177000950878:android:56b7d57a9816463f7d58cf',
    messagingSenderId: '177000950878',
    projectId: 'flashfeed-16793',
    storageBucket: 'flashfeed-16793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA2BLDWfcLEmEFH30Ijy_0ZKgO_QNlUHs',
    appId: '1:177000950878:ios:2cecc149335af5b97d58cf',
    messagingSenderId: '177000950878',
    projectId: 'flashfeed-16793',
    storageBucket: 'flashfeed-16793.appspot.com',
    androidClientId: '177000950878-sa38kghkdoa42p2vfjpt7j8mv5tff3ie.apps.googleusercontent.com',
    iosClientId: '177000950878-vuash98uitgpi4ruat56qcs98gbkarfp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashfeed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA2BLDWfcLEmEFH30Ijy_0ZKgO_QNlUHs',
    appId: '1:177000950878:ios:2288368b872512357d58cf',
    messagingSenderId: '177000950878',
    projectId: 'flashfeed-16793',
    storageBucket: 'flashfeed-16793.appspot.com',
    androidClientId: '177000950878-sa38kghkdoa42p2vfjpt7j8mv5tff3ie.apps.googleusercontent.com',
    iosClientId: '177000950878-mrev54gh4l41qj9l9tiubfe1pvddcfjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashfeed.RunnerTests',
  );
}
